# Rendezvous Environment Configuration
simulation:
  simulation_time: 1000.0
  time_step: 1.0
  dyn_rate: 0.1
  fsw_rate: 1.0
  max_step_duration: 1000000000.0
  time_limit: 1000.0
  log_level: WARNING
  render_mode: null
  variable_interval: true
  terminate_on_time_limit: false
  failure_penalty: -1.0
  vizard_dir: /home/parth/saif-autonomy/satellite_RL/vizard_output
  vizard_settings:
    show_spacecraft: [true, true]
    spacecraft_model: [bskSat, bskSat]
    generic_sensor_list: [[], []]

satellites:
  chief:
    name: ChiefSat
    initial_conditions:
      utc_init: 0.0
      oe: [7000000.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      mu: 398600441800000.0
    physical_properties:
      mass: 300.0
      dragCoeff: 2.2
      width: 1.38
      depth: 1.04
      height: 1.58
    power_system:
      storedCharge_Init: 50000.0
      batteryStorageCapacity: 100000.0
      panelEfficiency: 0.3
      panelArea: 1.0
      basePowerDraw: 0.0
    attitude_control:
      sigma_init: [0.0, 0.0, 0.0]
      omega_init: [0.0, 0.0, 0.0]
      wheelSpeeds: [0.0, 0.0, 0.0]
      maxWheelSpeed: 0.1
      u_max: 0.0

  deputy:
    name: DeputySat
    initial_conditions:
      utc_init: 0.0
      oe: [7001000.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      mu: 398600441800000.0
    physical_properties:
      mass: 250.0
      dragCoeff: 2.0
      width: 1.2
      depth: 0.9
      height: 1.3
    power_system:
      storedCharge_Init: 40000.0
      batteryStorageCapacity: 80000.0
      panelEfficiency: 0.3
      panelArea: 0.8
      basePowerDraw: 0.0
    attitude_control:
      sigma_init: [0.0, 0.0, 0.0]
      omega_init: [0.0, 0.0, 0.0]
      wheelSpeeds: [0.0, 0.0, 0.0]
      maxWheelSpeed: 0.1
      u_max: 0.0
    propulsion:
      dv_available_init: 100.0

relative_positioning:
  use_relative_setup: true
  chief_orbit_randomization:
    enabled: true
    altitude_range: [6800000.0, 7200000.0]
    inclination_range: [0.0, 0.1]
    eccentricity_range: [0.0, 0.01]
    raan_range: [0.0, 6.28]
    arg_periapsis_range: [0.0, 6.28]
    true_anomaly_range: [0.0, 6.28]
  deputy_relative_states:
    enabled: true
    position_ranges:
      radial_range: [-5000.0, 5000.0]
      along_track_range: [-10000.0, 10000.0]
      cross_track_range: [-2000.0, 2000.0]
    velocity_ranges:
      radial_velocity_range: [-5.0, 5.0]
      along_track_velocity_range: [-10.0, 10.0]
      cross_track_velocity_range: [-2.0, 2.0]
    training_scenarios:
      close_approach:
        position_ranges:
          radial_range: [-1000.0, 1000.0]
          along_track_range: [-2000.0, 2000.0]
          cross_track_range: [-500.0, 500.0]
        velocity_ranges:
          radial_velocity_range: [-2.0, 2.0]
          along_track_velocity_range: [-5.0, 5.0]
          cross_track_velocity_range: [-1.0, 1.0]
        weight: 0.4
      medium_range:
        position_ranges:
          radial_range: [-3000.0, 3000.0]
          along_track_range: [-6000.0, 6000.0]
          cross_track_range: [-1500.0, 1500.0]
        velocity_ranges:
          radial_velocity_range: [-3.0, 3.0]
          along_track_velocity_range: [-7.0, 7.0]
          cross_track_velocity_range: [-1.5, 1.5]
        weight: 0.4
      far_range:
        position_ranges:
          radial_range: [-5000.0, 5000.0]
          along_track_range: [-10000.0, 10000.0]
          cross_track_range: [-2000.0, 2000.0]
        velocity_ranges:
          radial_velocity_range: [-5.0, 5.0]
          along_track_velocity_range: [-10.0, 10.0]
          cross_track_velocity_range: [-2.0, 2.0]
        weight: 0.2
  constraints:
    max_relative_distance: 15000.0
    min_relative_distance: 100.0
    max_relative_velocity: 15.0
    collision_avoidance_distance: 50.0
    fuel_efficiency_target: 0.8

rewards:
  distance_reward_weight: -1.0
  distance_target: [0.0, 0.0, 0.0]
  velocity_reward_weight: -1.0
  velocity_target: [0.0, 0.0, 0.0]
  fuel_penalty_weight: -0.1
  collision_penalty: -100.0
  success_reward: 100.0
  time_penalty: -0.01

environment:
  world_type: BasicWorldModel
  world_args: {}
  communicator: null
  sat_arg_randomizer: null
  generate_obs_retasking_only: false
  dtype: float64